version: '3'
services:
  suggestion:
    image: "dtobtn/readability-lisibilite:latest"
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    working_dir: /app
    ports:
    - 5000:5000
    


  